spring.application.name: feature-flag

server:
  port: 8091

local:
  features:
    enabled-feature:
      enabled: true
      variants:
        - property-custom:
            param1: 1
            param2: "2"
            param3: true
            param4: [
              { "child": 1000 }
            ]
    disabled-feature:
      enabled: false
      variants: [ ]
    user-targeting-feature:
      enabled: true
      variants:
        - userId: 1234
        - userId: 5678
    deployment-feature:
      enabled: true
      variants:
        - rolloutPercentage: 10

api:
  amplitude:
    url: https://experiment.amplitude.com
    secretKey: ''
